version: '3.8'
services:
  # Backend service (Spring Boot)
  app-backend:
    image: school-management-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: client  # Utilisation du profil client
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/schoolManagement4
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - /d/docker/uploads:/app/uploads  # Monte le dossier des uploads sur D:
      - /d/docker/images:/app/images  # Monte le dossier des images sur D:
    depends_on:
      - db
    logging:
      driver: "none"

  # Frontend service (Angular)
  app-frontend:
    build:
      context: /mnt/c/Users/djato/schoolManagement-front  # Ajuste le chemin selon ta configuration
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - app-backend
    logging:
      driver: "none"

  # Database service (PostgreSQL)
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schoolManagement4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "none"

volumes:
  postgres-data:
