version: '3.8'
services:
  mongodb:
    image: mongo:4.2
    container_name: graylog-mongo
    networks:
      - graylog
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: graylog-elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    networks:
      - graylog
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  graylog:
    image: graylog/graylog:3.3
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=g5Lk41H+LIPKqiX5t/5ic9RZSbgLht5Ua1E/ZwEUwLY=
      - GRAYLOG_ROOT_PASSWORD_SHA2=6feb4c700de1982f91ee7a1b40ca4ded05d155af3987597cb179f430dd60da0b
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_MONGODB_URI=mongodb://graylog-mongo:27017/graylog
    networks:
      - graylog
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
      - elasticsearch

networks:
  graylog:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local